// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdygqdfvzbrxzoroeper.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkeWdxZGZ2emJyeHpvcm9lcGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTQ3NDgsImV4cCI6MjA1ODMzMDc0OH0.9omoYNHPoU5bvYzc9uKOZcZBWvQWWbNEF4rCCX_duRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);